name: step_wise
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
   

  # Core
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  dartz: ^0.10.1

  # Firebase
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # Network
  http: ^1.2.1
  net_kit: ^4.0.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  lottie: ^3.1.2
  timeline_tile: ^2.0.0
  smooth_page_indicator: ^1.2.0+3
  uuid: ^4.5.1
  date_format: ^2.0.9
  intl: ^0.20.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code Generation
  build_runner: ^2.4.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/emotions/
    - assets/images/tools/
    - assets/images/aim/
    - assets/images/onboard/
    - assets/animations/
